config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'search/query'
  get 'search' => "search#new"
  resources :jobs
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'log_out' => "sessions#destroy", :as => "log_out"
  get 'log_in' => "sessions#new", :as => "log_in"
  get 'sign_up' => 'users#new', :as => "sign_up"
  root 'welcome#index'
  resources :sessions
  resources :users
  resources :tags
  resources :posts
  resources :periods
  resources :parties
  resources :mps
  resources :elections
  resources :about
  resources :welcome
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/election.rb
class Election < ApplicationRecord
	belongs_to :mp
    belongs_to :period
    belongs_to :party
    
end

app/models/job.rb
class Job < ApplicationRecord
    has_and_belongs_to_many :mps

    def to_s
        self.name
    end
end

app/models/mp.rb
# frozen_string_literal: true

class Mp < ApplicationRecord
  validates :name, :surname, :gender, :birthdate, presence: true
  validate :olum_tarihi_dogum_tarihinden_kucuk_olamaz
  has_many :elections
  has_many :periods, through: :elections
  has_many :parties, through: :elections
  has_and_belongs_to_many  :jobs
  accepts_nested_attributes_for :elections, allow_destroy: true
  
  def olum_tarihi_dogum_tarihinden_kucuk_olamaz
    unless deaddate.nil?
      if deaddate < birthdate || deaddate == birthdate
        errors.add(:deaddate, 'Doğum tarihinden küçük ve eşit olamaz!')
      end
    end
  end

  def full_name
    "#{name}, #{name2} #{surname}"
  end
end

app/models/party.rb
class Party < ApplicationRecord
	has_many :elections
	has_many :mps, :through => :elections
	has_many :periods, :through => :elections

end

app/models/period.rb
# frozen_string_literal: true
class Period < ApplicationRecord
  has_many :elections
  has_many :mps, through: :elections
  has_many :parties, through: :elections
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/post.rb
class Post < ApplicationRecord
	has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/parties_controller.rb
# frozen_string_literal: true

class PartiesController < ApplicationController
  before_action :set_party, only: %i[show edit update destroy]
  before_action :yetkili?, only: %i[new create edit update destroy]
  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show; end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit; end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_party
    @party = Party.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def party_params
    params.require(:party).permit(:name, :shortname, :establishdate, :logo)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/election_helper.rb
module ElectionHelper
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mps_helper.rb
module MpsHelper
    def yetkili?
        if session[:user_id]
          true
        else
          respond_to {|format| format.html { redirect_to :mps, notice: "Yetkiniz yok." }      }  
        end
      end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/parties/_form.html.erb
<%= form_with(model: party, local: true) do |form| %>
  <% if party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
        <% party.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :shortname %>
    <%= form.text_field :shortname %>
  </div>

  <div class="field">
    <%= form.label :establishdate %>
    <%= form.date_select :establishdate %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.text_field :logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Siyasi Partiler</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Parti Adı</th>
      <th>Kısaltma</th>
      <th>Kuruluş Tarihi</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.name %></td>
        <td><%= party.shortname %></td>
        <td><%= party.establishdate %></td>
        <td><%= party.logo %></td>
        <td><%= link_to 'Ayrıntılar', party %></td>
        <td><%= link_to 'Düzenle', edit_party_path(party) %></td>
        <td><%= link_to 'Sil', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Yeni Parti Ekle', new_party_path %>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<%= javascript_include_tag "party" %>

<p id="notice"><%= notice %></p>

<p><%= image_tag( @party.logo ) %></p>
<p>
  <strong>Name:</strong>
  <%= @party.name %>
</p>

<p>
  <strong>Shortname:</strong>
  <%= @party.shortname %>
</p>

<p>
  <strong>Establishdate:</strong>
  <%= @party.establishdate %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @party.logo %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>